<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        // ── Users ─────────────────────────────────────────────────────────────
        DB::table('users')->insertOrIgnore([
            'name'           => 'Kominhoo Admin',
            'email'          => 'admin@kominhoo.com',
            'phone'          => '+2348000000000',
            'password'       => Hash::make('admin1234'),
            'role'           => 'admin',
            'skin_type'      => 'combination',
            'loyalty_points' => 0,
            'tier'           => 'Platinum',
            'created_at'     => now(),
            'updated_at'     => now(),
        ]);

        DB::table('users')->insertOrIgnore([
            'name'           => 'Amara Obi',
            'email'          => 'amara@example.com',
            'phone'          => '+2348012345678',
            'password'       => Hash::make('password'),
            'role'           => 'customer',
            'skin_type'      => 'oily',
            'loyalty_points' => 120,
            'tier'           => 'Silver',
            'created_at'     => now(),
            'updated_at'     => now(),
        ]);

        // ── Products (truncate + re-seed for clean data) ──────────────────────
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('bundle_product')->truncate();
        DB::table('bundles')->truncate();
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $products = [
            [
                'slug'         => 'cosrx-low-ph-good-morning-cleanser',
                'name'         => 'Low pH Good Morning Cleanser',
                'brand'        => 'COSRX',
                'category'     => 'Cleanser',
                'price'        => 12500.00,
                'original_price' => null,
                'stock'        => 80,
                'skin_types'   => json_encode(['Oily', 'Combination']),
                'concerns'     => json_encode(['Acne', 'Pores', 'Texture']),
                'sensitivity'  => 'Sensitive',
                'routine_step' => 'Cleanser',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Gel',
                'ingredients'  => json_encode(['Salicylic Acid', 'BHA']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop&q=80']),
                'size'         => '150ml',
                'badge'        => 'Best Seller',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.70,
                'review_count' => 1243,
                'description'  => 'A gentle, low-pH cleanser that removes impurities without stripping your skin barrier. Ideal as a first step in any AM or PM routine.',
            ],
            [
                'slug'         => 'cosrx-snail-mucin-96-power-repairing-essence',
                'name'         => 'Snail Mucin 96% Power Repairing Essence',
                'brand'        => 'COSRX',
                'category'     => 'Essence',
                'price'        => 18000.00,
                'original_price' => 22000.00,
                'stock'        => 65,
                'skin_types'   => json_encode(['Dry', 'Normal', 'Combination']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines', 'Texture']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Essence',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Snail Mucin', 'Hyaluronic Acid']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1620916566396-4c7aa9a87879?w=600&h=600&fit=crop&q=80']),
                'size'         => '100ml',
                'badge'        => 'Fan Fave',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.90,
                'review_count' => 3587,
                'description'  => '96% snail secretion filtrate essence that repairs, hydrates and brightens skin overnight. A COSRX bestseller trusted by millions worldwide.',
            ],
            [
                'slug'         => 'laneige-cream-skin-toner-moisturizer',
                'name'         => 'Cream Skin Toner & Moisturizer',
                'brand'        => 'Laneige',
                'category'     => 'Toner',
                'price'        => 28500.00,
                'original_price' => null,
                'stock'        => 42,
                'skin_types'   => json_encode(['Dry', 'Normal']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Toner',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Cream',
                'ingredients'  => json_encode(['Ceramides', 'White Leaf Water']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&h=600&fit=crop&q=80']),
                'size'         => '150ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.60,
                'review_count' => 876,
                'description'  => 'A creamy toner that delivers a surge of moisture while strengthening the skin barrier. Two-in-one hydration that cuts steps from your routine.',
            ],
            [
                'slug'         => 'some-by-mi-aha-bha-pha-miracle-toner',
                'name'         => 'AHA BHA PHA 30 Days Miracle Toner',
                'brand'        => 'Some By Mi',
                'category'     => 'Toner',
                'price'        => 15500.00,
                'original_price' => 18000.00,
                'stock'        => 90,
                'skin_types'   => json_encode(['Oily', 'Combination']),
                'concerns'     => json_encode(['Acne', 'Texture', 'Large Pores']),
                'sensitivity'  => 'Medium',
                'routine_step' => 'Toner',
                'time_of_use'  => 'PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['AHA', 'BHA', 'PHA', 'Centella Asiatica']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1614289371518-722f2615943d?w=600&h=600&fit=crop&q=80']),
                'size'         => '150ml',
                'badge'        => 'Sale',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.50,
                'review_count' => 2109,
                'description'  => 'Triple acid toner that visibly reduces acne, blackheads and uneven texture in 30 days of consistent use.',
            ],
            [
                'slug'         => 'the-ordinary-10-niacinamide-zinc-serum',
                'name'         => '10% Niacinamide + 1% Zinc Serum',
                'brand'        => 'The Ordinary',
                'category'     => 'Serum',
                'price'        => 8500.00,
                'original_price' => null,
                'stock'        => 120,
                'skin_types'   => json_encode(['Oily', 'Combination', 'Normal']),
                'concerns'     => json_encode(['Acne', 'Large Pores', 'Dullness', 'Hyperpigmentation']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Serum',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Niacinamide', 'Zinc PCA']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => 'Best Value',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.40,
                'review_count' => 4821,
                'description'  => 'High-strength vitamin B3 formula that targets excess sebum, blemishes and pore appearance. The most affordable actives serum on the market.',
            ],
            [
                'slug'         => 'beauty-of-joseon-tone-up-sun-serum-spf50',
                'name'         => 'Tone Up Sun Serum SPF 50+ PA++++',
                'brand'        => 'Beauty of Joseon',
                'category'     => 'Sunscreen',
                'price'        => 22000.00,
                'original_price' => null,
                'stock'        => 55,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Hyperpigmentation', 'Dullness', 'Fine Lines']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Sunscreen',
                'time_of_use'  => 'AM',
                'texture'      => 'Lotion',
                'ingredients'  => json_encode(['Niacinamide', 'Rice Extract', 'Propolis']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop&q=80']),
                'size'         => '50ml',
                'badge'        => 'Staff Pick',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.80,
                'review_count' => 2931,
                'description'  => 'Lightweight sun serum that protects, brightens and tones in one effortless step. A cult favourite in the Nigerian heat.',
            ],
            [
                'slug'         => 'anua-heartleaf-pore-concentrate-serum',
                'name'         => 'Heartleaf Quercetinol Pore Concentrate Serum',
                'brand'        => 'Anua',
                'category'     => 'Serum',
                'price'        => 24000.00,
                'original_price' => 29000.00,
                'stock'        => 38,
                'skin_types'   => json_encode(['Oily', 'Combination', 'Sensitive']),
                'concerns'     => json_encode(['Acne', 'Redness', 'Large Pores']),
                'sensitivity'  => 'Sensitive',
                'routine_step' => 'Serum',
                'time_of_use'  => 'PM',
                'texture'      => 'Lotion',
                'ingredients'  => json_encode(['Centella Asiatica', 'Heartleaf', 'Niacinamide']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1570194065650-d99fb4b38f34?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => 'New',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.70,
                'review_count' => 1654,
                'description'  => 'Heartleaf-powered serum that calms redness, tightens pores and controls excess oil for clearer, more refined skin.',
            ],
            [
                'slug'         => 'klairs-freshly-juiced-vitamin-c-serum',
                'name'         => 'Freshly Juiced Vitamin C Serum',
                'brand'        => 'Klairs',
                'category'     => 'Serum',
                'price'        => 32000.00,
                'original_price' => null,
                'stock'        => 30,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Hyperpigmentation', 'Dullness', 'Fine Lines']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Serum',
                'time_of_use'  => 'PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Vitamin C', 'Hyaluronic Acid', 'Peptides']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&q=80']),
                'size'         => '35ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.60,
                'review_count' => 987,
                'description'  => 'Gentle 5% vitamin C serum that brightens, evens tone and fades dark spots without irritation. Perfect for melanin-rich skin.',
            ],
            [
                'slug'         => 'innisfree-green-tea-seed-deep-cream',
                'name'         => 'Green Tea Seed Deep Cream',
                'brand'        => 'Innisfree',
                'category'     => 'Moisturizer',
                'price'        => 19500.00,
                'original_price' => 23000.00,
                'stock'        => 50,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Moisturizer',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Cream',
                'ingredients'  => json_encode(['Green Tea', 'Hyaluronic Acid', 'Ceramides']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop&q=80']),
                'size'         => '50ml',
                'badge'        => 'Sale',
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.50,
                'review_count' => 2345,
                'description'  => 'Rich, antioxidant moisturizer packed with Jeju green tea that deeply hydrates and repairs the skin barrier.',
            ],
            [
                'slug'         => 'purito-centella-unscented-toner',
                'name'         => 'Centella Unscented Toner',
                'brand'        => 'Purito',
                'category'     => 'Toner',
                'price'        => 14500.00,
                'original_price' => null,
                'stock'        => 70,
                'skin_types'   => json_encode(['Sensitive', 'Dry', 'Normal']),
                'concerns'     => json_encode(['Redness', 'Dehydration', 'Acne']),
                'sensitivity'  => 'Sensitive',
                'routine_step' => 'Toner',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Centella Asiatica', 'PHA', 'Hyaluronic Acid']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1596564100009-9b6fcf02e2ff?w=600&h=600&fit=crop&q=80']),
                'size'         => '200ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.60,
                'review_count' => 1432,
                'description'  => 'Fragrance-free centella toner that soothes, hydrates and gently exfoliates sensitive skin without any irritation.',
            ],
            [
                'slug'         => 'dr-jart-real-cica-144-soothing-ampoule',
                'name'         => 'Real Cica 144 Soothing Ampoule',
                'brand'        => 'Dr.Jart+',
                'category'     => 'Serum',
                'price'        => 38500.00,
                'original_price' => null,
                'stock'        => 25,
                'skin_types'   => json_encode(['Sensitive', 'Dry', 'Combination']),
                'concerns'     => json_encode(['Redness', 'Acne', 'Dehydration']),
                'sensitivity'  => 'Sensitive',
                'routine_step' => 'Serum',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Centella Asiatica', 'Salicornia', 'Madecassoside']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => 'Staff Pick',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.80,
                'review_count' => 734,
                'description'  => '144-hour moisture retention ampoule packed with Cica actives for intensely calm, clear skin. The ultimate sensitive skin SOS.',
            ],
            [
                'slug'         => 'klairs-pure-vitamin-c-21-5-advanced-serum',
                'name'         => 'Pure Vitamin C 21.5 Advanced Serum',
                'brand'        => 'Klairs',
                'category'     => 'Serum',
                'price'        => 45000.00,
                'original_price' => 52000.00,
                'stock'        => 20,
                'skin_types'   => json_encode(['Normal', 'Combination', 'Oily']),
                'concerns'     => json_encode(['Hyperpigmentation', 'Fine Lines', 'Dullness']),
                'sensitivity'  => 'Medium',
                'routine_step' => 'Serum',
                'time_of_use'  => 'PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Vitamin C', 'Vitamin E', 'Hyaluronic Acid']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&h=600&fit=crop&q=80']),
                'size'         => '35ml',
                'badge'        => 'Sale',
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.60,
                'review_count' => 512,
                'description'  => 'High-potency 21.5% vitamin C serum for dramatic brightening and anti-aging results. Use with caution if new to actives.',
            ],
            [
                'slug'         => 'cosrx-oil-free-matte-gel-moisturizer',
                'name'         => 'Oil-Free Matte Gel Moisturizer',
                'brand'        => 'COSRX',
                'category'     => 'Moisturizer',
                'price'        => 17000.00,
                'original_price' => null,
                'stock'        => 60,
                'skin_types'   => json_encode(['Oily', 'Combination']),
                'concerns'     => json_encode(['Acne', 'Large Pores', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Moisturizer',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Gel',
                'ingredients'  => json_encode(['Niacinamide', 'Hyaluronic Acid', 'Birch Sap']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1557053910-d9eadeed1c58?w=600&h=600&fit=crop&q=80']),
                'size'         => '100ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.50,
                'review_count' => 867,
                'description'  => 'Feather-light gel moisturizer that hydrates without clogging pores or leaving residue — ideal for Nigerian humidity.',
            ],
            [
                'slug'         => 'the-ordinary-alpha-arbutin-2-ha-serum',
                'name'         => 'Alpha Arbutin 2% + HA Serum',
                'brand'        => 'The Ordinary',
                'category'     => 'Serum',
                'price'        => 9500.00,
                'original_price' => null,
                'stock'        => 100,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Hyperpigmentation', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Serum',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Arbutin', 'Hyaluronic Acid']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1616616622481-0a10ae0e15e1?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => 'Best Value',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.30,
                'review_count' => 3201,
                'description'  => 'Targeted brightening serum that inhibits melanin production and fades dark spots over time. Best for post-acne marks.',
            ],
            [
                'slug'         => 'beauty-of-joseon-propolis-energy-ampule',
                'name'         => 'Propolis Energy Ampule',
                'brand'        => 'Beauty of Joseon',
                'category'     => 'Serum',
                'price'        => 26500.00,
                'original_price' => 32000.00,
                'stock'        => 45,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Dullness', 'Dehydration', 'Fine Lines']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Serum',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Lotion',
                'ingredients'  => json_encode(['Propolis', 'Niacinamide', 'Peptides']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1582560475093-ba66accbc095?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => 'Sale',
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.70,
                'review_count' => 1876,
                'description'  => 'Golden propolis ampoule that glows up dull, tired skin with rich antioxidants and peptides. Gives an instant glass-skin effect.',
            ],
            [
                'slug'         => 'laneige-water-bank-blue-ha-serum',
                'name'         => 'Water Bank Blue HA Serum',
                'brand'        => 'Laneige',
                'category'     => 'Serum',
                'price'        => 42000.00,
                'original_price' => null,
                'stock'        => 28,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Serum',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['Hyaluronic Acid', 'Blue Hyaluronic Acid', 'Niacinamide']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&h=600&fit=crop&q=80']),
                'size'         => '40ml',
                'badge'        => 'New',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.80,
                'review_count' => 643,
                'description'  => 'Next-gen hydration serum with 5 types of hyaluronic acid that lock in moisture for 72 hours. Plumps skin from within.',
            ],
            [
                'slug'         => 'laneige-lip-sleeping-mask',
                'name'         => 'Lip Sleeping Mask',
                'brand'        => 'Laneige',
                'category'     => 'Mask',
                'price'        => 29000.00,
                'original_price' => 35000.00,
                'stock'        => 75,
                'skin_types'   => json_encode(['Dry', 'Normal', 'Combination']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Mask',
                'time_of_use'  => 'PM',
                'texture'      => 'Gel',
                'ingredients'  => json_encode(['Hyaluronic Acid', 'Ceramides', 'Squalane']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=600&h=600&fit=crop&q=80']),
                'size'         => '70ml',
                'badge'        => 'Iconic',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.90,
                'review_count' => 5218,
                'description'  => 'Cult-classic overnight sleep mask that transforms dry, dull skin into plump perfection by morning.',
            ],
            [
                'slug'         => 'the-ordinary-retinol-0-2-in-squalane',
                'name'         => 'Retinol 0.2% in Squalane',
                'brand'        => 'The Ordinary',
                'category'     => 'Treatment',
                'price'        => 11500.00,
                'original_price' => null,
                'stock'        => 55,
                'skin_types'   => json_encode(['Normal', 'Combination', 'Oily']),
                'concerns'     => json_encode(['Fine Lines', 'Wrinkles', 'Texture']),
                'sensitivity'  => 'Medium',
                'routine_step' => 'Treatment',
                'time_of_use'  => 'PM',
                'texture'      => 'Oil',
                'ingredients'  => json_encode(['Retinol', 'Squalane']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1555487505-8603a1a69755?w=600&h=600&fit=crop&q=80']),
                'size'         => '30ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.40,
                'review_count' => 2987,
                'description'  => 'Entry-level retinol formula in squalane for gentle anti-aging without over-drying. Introduce slowly — 2-3 nights per week.',
            ],
            [
                'slug'         => 'innisfree-pore-minimizing-toner',
                'name'         => 'Pore Minimizing Toner',
                'brand'        => 'Innisfree',
                'category'     => 'Toner',
                'price'        => 16500.00,
                'original_price' => null,
                'stock'        => 48,
                'skin_types'   => json_encode(['Oily', 'Combination']),
                'concerns'     => json_encode(['Large Pores', 'Acne', 'Texture']),
                'sensitivity'  => 'Medium',
                'routine_step' => 'Toner',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Water',
                'ingredients'  => json_encode(['BHA', 'Salicylic Acid', 'Green Tea']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1545208935-9a7b23524f41?w=600&h=600&fit=crop&q=80']),
                'size'         => '150ml',
                'badge'        => null,
                'is_featured'  => false,
                'is_active'    => true,
                'rating'       => 4.30,
                'review_count' => 1109,
                'description'  => 'BHA-powered toner that visibly minimizes pores, controls oil and refines skin texture with each use.',
            ],
            [
                'slug'         => 'clinique-moisture-surge-100h-hydrator',
                'name'         => 'Moisture Surge 100H Auto-Replenishing Hydrator',
                'brand'        => 'Clinique',
                'category'     => 'Moisturizer',
                'price'        => 52000.00,
                'original_price' => 65000.00,
                'stock'        => 18,
                'skin_types'   => json_encode(['All']),
                'concerns'     => json_encode(['Dehydration', 'Fine Lines', 'Dullness']),
                'sensitivity'  => 'Low',
                'routine_step' => 'Moisturizer',
                'time_of_use'  => 'AM/PM',
                'texture'      => 'Gel',
                'ingredients'  => json_encode(['Aloe Vera', 'Hyaluronic Acid', 'Activated Aloe Water']),
                'images'       => json_encode(['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&q=80']),
                'size'         => '50ml',
                'badge'        => 'Luxury Pick',
                'is_featured'  => true,
                'is_active'    => true,
                'rating'       => 4.70,
                'review_count' => 4322,
                'description'  => '100-hour continuous hydration gel that auto-replenishes moisture as the day goes on. The gold standard in western skincare.',
            ],
        ];

        // ── Auto-build ingredient_info and pro_tip from product data ─────────
        $ingredientLib = [
            'Salicylic Acid'       => 'Penetrates pores to dissolve blackheads and reduce breakouts',
            'BHA'                  => 'Oil-soluble exfoliant that deep-cleans inside pores',
            'Snail Mucin'          => 'Repairs skin barrier and boosts collagen production',
            'Hyaluronic Acid'      => 'Holds up to 1,000× its weight in water for deep hydration',
            'Niacinamide'          => 'Brightens skin, visibly minimizes pores, and controls sebum',
            'Zinc PCA'             => 'Regulates excess oil production and calms inflammation',
            'Ceramides'            => 'Restores and strengthens the protective skin barrier',
            'White Leaf Water'     => 'Delivers intense hydration and soothes sensitivity',
            'AHA'                  => 'Water-soluble exfoliant that smooths uneven skin texture',
            'PHA'                  => 'Gentle next-gen exfoliant safe for even sensitive skin',
            'Centella Asiatica'    => 'Calming botanical powerhouse that reduces redness and irritation',
            'Heartleaf'            => 'Soothes stressed, reactive skin and controls inflammation',
            'Vitamin C'            => 'Brightens dark spots, evens tone, and defends against free radicals',
            'Vitamin E'            => 'Antioxidant that conditions and protects the skin barrier',
            'Peptides'             => 'Signaling proteins that stimulate collagen and firm the skin',
            'Green Tea'            => 'Rich antioxidants fight free radicals and soothe irritation',
            'Retinol'              => 'Gold-standard anti-aging ingredient for fine lines and texture',
            'Squalane'             => 'Lightweight plant-derived oil that moisturizes without greasiness',
            'Propolis'             => 'Natural antibacterial that nourishes and soothes the skin',
            'Rice Extract'         => 'Brightens complexion and evens skin tone over time',
            'Arbutin'              => 'Inhibits melanin production to fade dark spots',
            'Salicornia'           => 'Marine ingredient packed with antioxidants and minerals',
            'Madecassoside'        => 'Cica extract that accelerates healing and calms redness',
            'Birch Sap'            => 'Hydrating antioxidant-rich tree water that energizes skin',
            'Aloe Vera'            => 'Soothes, hydrates, and calms inflammatory skin conditions',
            'Activated Aloe Water' => 'Advanced form of aloe for prolonged moisture delivery',
            'Blue Hyaluronic Acid' => 'Penetrates deeper skin layers for lasting plumpness',
        ];

        $proTipMap = [
            'Acne'              => 'Patch test first, then introduce slowly — 3× per week to start. Over-use can cause purging.',
            'Hyperpigmentation' => 'Consistency beats intensity — use daily for 8+ weeks and always pair with SPF for best results.',
            'Fine Lines'        => 'Pairing this with a peptide moisturizer amplifies the anti-aging benefit significantly.',
            'Redness'           => 'Apply with clean fingertips using gentle press-and-hold motions — never drag across reactive skin.',
            'Dehydration'       => 'Apply to damp skin immediately after cleansing to lock in maximum moisture before it evaporates.',
            'Wrinkles'          => 'Less is more — a pea-sized amount covers the entire face. Start with 2 nights per week.',
            'Large Pores'       => 'Use a toner before application to clear any residual oil so actives can fully penetrate.',
            'Dullness'          => 'Layer this under your moisturizer nightly and you will see a visible glow within 2 weeks.',
        ];

        foreach ($products as &$product) {
            $ings = json_decode($product['ingredients'] ?? '[]', true) ?? [];
            $info = [];
            foreach ($ings as $ing) {
                if (isset($ingredientLib[$ing])) $info[$ing] = $ingredientLib[$ing];
            }
            $product['ingredient_info'] = json_encode($info);

            $concerns = json_decode($product['concerns'] ?? '[]', true) ?? [];
            $tip = 'Apply to slightly damp skin to seal in extra hydration from your toner or essence.';
            foreach ($proTipMap as $concern => $tipText) {
                if (in_array($concern, $concerns)) { $tip = $tipText; break; }
            }
            $product['pro_tip'] = $tip;
        }
        unset($product);

        foreach ($products as $product) {
            $product['created_at'] = now();
            $product['updated_at'] = now();
            DB::table('products')->insert($product);
        }

        // ── Bundles ───────────────────────────────────────────────────────────
        $bundle1Id = DB::table('bundles')->insertGetId([
            'name'           => 'Oily Skin Starter Kit',
            'slug'           => 'oily-skin-starter-kit',
            'description'    => 'Everything you need to control shine, clear pores, and keep oily skin balanced. Curated from best-selling K-beauty staples for Nigerian climate.',
            'price'          => 32000.00,
            'original_price' => 40500.00,
            'skin_type'      => 'oily',
            'is_active'      => true,
            'image'          => 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80',
            'created_at'     => now(),
            'updated_at'     => now(),
        ]);

        $bundle2Id = DB::table('bundles')->insertGetId([
            'name'           => 'Sensitive & Dry Skin Ritual',
            'slug'           => 'sensitive-dry-skin-ritual',
            'description'    => 'A gentle, fragrance-free routine for dry and easily irritated skin. Soothes, hydrates, and restores your skin barrier from day one.',
            'price'          => 46000.00,
            'original_price' => 61000.00,
            'skin_type'      => 'sensitive',
            'is_active'      => true,
            'image'          => 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80',
            'created_at'     => now(),
            'updated_at'     => now(),
        ]);

        // Bundle 1: AHA BHA Toner + Niacinamide Serum + Oil-Free Moisturizer
        $someByMiId  = DB::table('products')->where('slug', 'some-by-mi-aha-bha-pha-miracle-toner')->value('id');
        $niacinamideId = DB::table('products')->where('slug', 'the-ordinary-10-niacinamide-zinc-serum')->value('id');
        $oilFreeId   = DB::table('products')->where('slug', 'cosrx-oil-free-matte-gel-moisturizer')->value('id');

        // Bundle 2: Purito Toner + Snail Mucin + Laneige Cream Skin
        $purutoId    = DB::table('products')->where('slug', 'purito-centella-unscented-toner')->value('id');
        $snailId     = DB::table('products')->where('slug', 'cosrx-snail-mucin-96-power-repairing-essence')->value('id');
        $laneigeToner = DB::table('products')->where('slug', 'laneige-cream-skin-toner-moisturizer')->value('id');

        $pivots = [
            ['bundle_id' => $bundle1Id, 'product_id' => $someByMiId,   'quantity' => 1],
            ['bundle_id' => $bundle1Id, 'product_id' => $niacinamideId, 'quantity' => 1],
            ['bundle_id' => $bundle1Id, 'product_id' => $oilFreeId,    'quantity' => 1],
            ['bundle_id' => $bundle2Id, 'product_id' => $purutoId,     'quantity' => 1],
            ['bundle_id' => $bundle2Id, 'product_id' => $snailId,      'quantity' => 1],
            ['bundle_id' => $bundle2Id, 'product_id' => $laneigeToner, 'quantity' => 1],
        ];
        foreach ($pivots as $pivot) {
            if ($pivot['product_id']) DB::table('bundle_product')->insertOrIgnore($pivot);
        }

        // ── Guides ────────────────────────────────────────────────────────────
        $guides = [
            [
                'title'        => 'The 10-Step Korean Skincare Routine — Adapted for Nigerian Weather',
                'slug'         => 'korean-skincare-routine-nigerian-weather',
                'excerpt'      => 'K-beauty routines were designed for cold, dry Korean winters. Here\'s how to adapt them for Lagos heat and humidity without clogging pores.',
                'body'         => 'Nigerian skin faces unique challenges: intense UV, high humidity, and harmattan dryness. The classic 10-step routine needs thoughtful adaptation for the local climate.',
                'category'     => 'routine',
                'author'       => 'Kominhoo Editorial',
                'image'        => 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=80',
                'is_published' => true,
            ],
            [
                'title'        => 'Understanding Your Skin Type: The Nigerian Skin Guide',
                'slug'         => 'understanding-skin-type-nigerian-guide',
                'excerpt'      => 'Oily T-zone in the afternoon? Tight cheeks in the morning? You might not be what you think. Learn how to accurately identify your skin type.',
                'body'         => 'Most people with Nigerian skin self-diagnose as "oily" when they might actually be dehydrated combination skin. Here\'s how to tell the difference.',
                'category'     => 'education',
                'author'       => 'Kominhoo Editorial',
                'image'        => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
                'is_published' => true,
            ],
            [
                'title'        => 'Ingredients That Actually Work on Melanin-Rich Skin',
                'slug'         => 'ingredients-for-melanin-rich-skin',
                'excerpt'      => 'Niacinamide, tranexamic acid, vitamin C — but which form, which percentage? A science-backed guide to brightening darker skin tones safely.',
                'body'         => 'Post-inflammatory hyperpigmentation (PIH) is the number one skin concern for people with melanin-rich skin. K-beauty has the best answers.',
                'category'     => 'ingredients',
                'author'       => 'Kominhoo Editorial',
                'image'        => 'https://images.unsplash.com/photo-1570194065650-d99fb4ee0e02?w=800&q=80',
                'is_published' => true,
            ],
        ];
        foreach ($guides as $guide) {
            $guide['created_at'] = now();
            $guide['updated_at'] = now();
            DB::table('guides')->insertOrIgnore($guide);
        }


        // ── Promotions ────────────────────────────────────────────────────────
        $promotions = [
            [
                'code'          => 'WELCOME10',
                'name'          => '10% off your first order',
                'type'          => 'percentage',
                'value'         => 10.00,
                'minimum_order' => 5000.00,
                'usage_limit'   => 500,
                'used_count'    => 0,
                'expires_at'    => now()->addYear(),
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'code'          => 'KBEAUTY2K',
                'name'          => '₦2,000 off orders over ₦20,000',
                'type'          => 'fixed',
                'value'         => 2000.00,
                'minimum_order' => 20000.00,
                'usage_limit'   => 200,
                'used_count'    => 0,
                'expires_at'    => now()->addMonths(6),
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ];
        foreach ($promotions as $promo) {
            DB::table('promotions')->insertOrIgnore($promo);
        }
    }
}
